export interface AlgorithmDocumentation {
    id: string;
    idea: string;
    pseudocode: string[];
    invariant: string;
    pitfalls: string[];
}

export const documentation: AlgorithmDocumentation[] = [
    {
        id: 'bfs',
        idea: 'Busca genérica em que, dentre todos os vértices marcados e incidentes a alguma aresta ainda não explorada, escolhe-se sempre o menos recentemente alcançado — critério implementado por uma fila. Cada vértice recebe um índice L[v] (ordem de descoberta) e um nível[v] (distância à raiz em número de arestas).',
        pseudocode: [
            'Inicialização / Chamada inicial',
            '  t ← 0; Fila ← ∅',
            '  para todo vértice v ∈ V(G) faça',
            '    L[v] ← 0; nível[v] ← 0; pai[v] ← nulo',
            '  enquanto existir algum vértice v tal que L[v] = 0 efetuar',
            '    t ← t + 1; L[v] ← t          // v é a raiz da busca',
            '    Fila.Insere(v)',
            '    Executar Busca_Largura()',
            '',
            'Busca_Largura()',
            '  enquanto not Fila.Vazia() efetuar',
            '    v ← Fila.Remove()',
            '    para todo vértice w ∈ Γ(v) faça',
            '      se L[w] = 0 então          // aresta de árvore (ou pai)',
            '        pai[w] ← v; nível[w] ← nível[v] + 1',
            '        t ← t + 1; L[w] ← t; Fila.Insere(w)',
            '      senão se nível[w] = nível[v] + 1 então',
            '        Visitar aresta de tio {v, w}',
            '      senão se nível[w] = nível[v] e pai[v] = pai[w] e L[w] > L[v] então',
            '        Visitar aresta de irmão {v, w}',
            '      senão se nível[w] = nível[v] e pai[v] ≠ pai[w] e L[w] > L[v] então',
            '        Visitar aresta de primo {v, w}',
        ],
        invariant:
            'nível[w] = nível[pai[w]] + 1 para todo w ≠ raiz. Assim, no momento em que w é marcado, nível[w] já é a distância (número de arestas) entre a raiz da busca e w.',
        pitfalls: [
            'Marcar o vértice (atribuir L[w]) apenas quando ele sai da fila, e não quando entra: o mesmo vértice acabaria enfileirado várias vezes.',
            'Esquecer a condição L[w] > L[v] ao classificar arestas de irmão e de primo — ela garante que cada aresta seja explorada uma única vez.',
            'Em grafo ponderado, a busca em largura só devolve caminho de custo mínimo se todos os custos forem iguais; ela minimiza o número de arestas, não o custo.',
        ],
    },
    {
        id: 'dfs',
        idea: 'Busca genérica em que, dentre todos os vértices marcados e incidentes a alguma aresta ainda não explorada, escolhe-se sempre o mais recentemente alcançado. Cada vértice recebe um tempo de descoberta TD[v] e um tempo de término TT[v], marcados por um contador global t.',
        pseudocode: [
            'Inicialização / Chamada inicial',
            '  t ← 0',
            '  para todo vértice v ∈ V(G) faça',
            '    TD[v] ← 0; TT[v] ← 0; pai[v] ← nulo',
            '  enquanto existir algum vértice v tal que TD[v] = 0 efetuar',
            '    Executar Busca_Profundidade(v)   // v é a raiz da busca',
            '',
            'Busca_Profundidade(v)   — grafo não direcionado',
            '  t ← t + 1; TD[v] ← t',
            '  para todo vértice w ∈ Γ(v) faça',
            '    se TD[w] = 0 então              // aresta de árvore',
            '      pai[w] ← v; Executar Busca_Profundidade(w)',
            '    senão se TT[w] = 0 e w ≠ pai[v] então',
            '      Visitar aresta de retorno {v, w}',
            '  t ← t + 1; TT[v] ← t',
            '',
            'Busca_Profundidade(v)   — grafo direcionado',
            '  para todo vértice w ∈ Γ⁺(v) faça',
            '    se TD[w] = 0 então  aresta de árvore (v, w); pai[w] ← v; ...',
            '    senão se TT[w] = 0 então          aresta de retorno (v, w)',
            '    senão se TD[v] < TD[w] então      aresta de avanço (v, w)',
            '    senão                             aresta de cruzamento (v, w)',
        ],
        invariant:
            'Os intervalos de vida I(v) = [TD[v], TT[v]] são encaixados ou disjuntos, nunca se cruzam parcialmente. O vértice w é descendente de v se e somente se I(w) está contido em I(v).',
        pitfalls: [
            'Em grafo não direcionado só existem arestas de árvore e de retorno; avanço e cruzamento só aparecem em grafo direcionado.',
            'Esquecer a condição w ≠ pai[v]: a aresta usada para chegar em v não é aresta de retorno.',
            'Toda aresta de retorno evidencia um ciclo no grafo original — em grafo direcionado, ela é a única evidência necessária.',
        ],
    },
    {
        id: 'kosaraju',
        idea: 'Uma primeira busca em profundidade em G registra os tempos de término TT. A segunda busca, feita no grafo reverso Gᴿ e tomando os vértices em ordem decrescente de TT, produz uma floresta em que cada árvore é exatamente um componente fortemente conexo (f-conexo).',
        pseudocode: [
            'Método de Kosaraju',
            '  1. Fazer busca em profundidade em G',
            '       // salvar os tempos de término TT de cada vértice',
            '  2. Construir o grafo reverso (ou transposto) Gᴿ',
            '       // se (v, w) ∈ E(G) então (w, v) ∈ E(Gᴿ)',
            '  3. Fazer busca em profundidade em Gᴿ tomando os vértices',
            '     em ordem decrescente de TT',
            '',
            '  Cada árvore da floresta de profundidade obtida no passo 3',
            '  corresponde a um componente fortemente conexo de G.',
        ],
        invariant:
            'A ordem decrescente de tempo de término garante que a busca em Gᴿ iniciada em um vértice nunca escapa do componente f-conexo a que ele pertence.',
        pitfalls: [
            'Esquecer de construir o grafo reverso Gᴿ antes da segunda busca.',
            'Percorrer a segunda busca na ordem crescente de TT em vez da decrescente.',
            'Confundir os três níveis de conectividade de um grafo direcionado conexo: s-conexo (grafo subjacente conexo), sf-conexo (para todo par, um alcança o outro) e f-conexo (todos mutuamente alcançáveis).',
        ],
    },
    {
        id: 'prim',
        idea: 'Constrói a AGM incluindo vértices, um a um, de forma gulosa. Partindo de uma raiz r, a cada passo acrescenta a aresta de menor custo com uma extremidade em V(T) (já selecionados) e a outra fora de V(T).',
        pseudocode: [
            'Método de Prim',
            '  1. Escolher um vértice qualquer r ∈ V(G)   // raiz',
            '  2. V(T) ← { r }        // conj. de vértices selecionados',
            '  3. E(T) ← ∅            // conj. de arestas da AGM',
            '  4. enquanto V(T) ≠ V(G) efetuar',
            '     a. Encontrar a aresta {v, w} de menor custo tal que',
            '        v ∈ V(T) e w ∉ V(T)',
            '     b. Acrescentar w a V(T)',
            '     c. Acrescentar {v, w} a E(T)',
            '',
            '  Custo total: C(T) = Σ  c  , para e ∈ E(T)',
            '                        e',
        ],
        invariant:
            'A cada iteração, T = (V(T), E(T)) é uma árvore e está contida em alguma árvore geradora de custo mínimo de G.',
        pitfalls: [
            'Comparar o custo da aresta com a distância acumulada desde a raiz em vez do custo da própria aresta — isso transformaria Prim em Dijkstra.',
            'Aplicar Prim em grafo direcionado: o problema correto passa a ser o de arborescência de custo mínimo.',
            'Em grafo desconexo não existe árvore geradora: um grafo G possui árvore geradora se e somente se G for conexo.',
        ],
    },
    {
        id: 'kruskal',
        idea: 'Constrói a AGM incluindo arestas, e não vértices como em Prim. Ordena as arestas em ordem não decrescente de custo e aceita, a cada iteração, a aresta de menor custo que não forme ciclo com as já inseridas em E(T).',
        pseudocode: [
            'Método de Kruskal',
            '  1. Ordenar as arestas em ordem não decrescente de custo:',
            '     e₁, e₂, e₃, . . .',
            '  2. V(T) ← V(G)      // todos os vértices entram na AGM',
            '  3. E(T) ← { e₁ }',
            '  4. j ← 2            // aresta a ser analisada',
            '  5. enquanto | E(T) | < | V(T) | − 1 efetuar',
            '     a. se a aresta e  não forma ciclo com as arestas de E(T)',
            '                     j',
            '        então Acrescentar e  a E(T)',
            '                            j',
            '     b. j ← j + 1',
        ],
        invariant:
            'A cada iteração, T = (V(T), E(T)) é uma floresta geradora contida em alguma árvore geradora de custo mínimo de G.',
        pitfalls: [
            'Supor que bastam n − 1 iterações: são necessárias pelo menos n − 1, mas podem ser mais, pois arestas que formam ciclo precisam ser ignoradas.',
            'Aceitar uma aresta cujos extremos já estão ligados por arestas de E(T): ela fecharia um ciclo.',
            'Em grafo desconexo o resultado é uma floresta geradora mínima, não uma árvore geradora.',
        ],
    },
    {
        id: 'dijkstra',
        idea: 'Resolve o problema de caminho mínimo a partir de uma única raiz s. Baseia-se no princípio da relaxação e "fecha" um vértice por iteração: escolhe o vértice ainda não fechado com o menor valor de dist e relaxa as arestas tensas que saem dele.',
        pseudocode: [
            'Operação de relaxação',
            '  se dist[v] + d    < dist[w] então   // aresta (v, w) está tensa?',
            '                vw',
            '    dist[w] ← dist[v] + d',
            '                          vw',
            '    pred[w] ← v',
            '',
            'Método de Dijkstra',
            '  1. para todo vértice v ∈ V(G) faça',
            '       dist[v] ← ∞; pred[v] ← nulo',
            '  2. dist[s] ← 0        // s é a raiz da busca',
            '  3. S ← ∅              // conjunto dos vértices fechados',
            '  4. enquanto S ≠ V(G) efetuar',
            '     a. Escolher o vértice v ∉ S de menor dist[v]',
            '     b. S ← S ∪ { v }                  // "fechar" o vértice v',
            '     c. para todo vértice w ∈ Γ⁺(v) faça',
            '          se dist[w] > dist[v] + d    então   // aresta tensa?',
            '                                    vw',
            '            dist[w] ← dist[v] + d',
            '                                  vw',
            '            pred[w] ← v',
        ],
        invariant:
            'Para todo v ∈ S, dist[v] já é o custo do caminho mínimo da raiz até v. Ao final, dist[ ] guarda os custos dos caminhos mínimos — os caminhos em si são recuperados pela lista de predecessores pred[ ].',
        pitfalls: [
            'Aplicar o método em grafo com aresta de custo negativo: ele falha. Reponderar, adicionando uma constante a todas as arestas, também pode falhar.',
            'Reabrir um vértice que já pertence a S: uma vez fechado, seu dist não muda mais.',
            'Achar que dist[ ] devolve os caminhos: sem pred[ ] obtêm-se apenas os custos.',
        ],
    },
    {
        id: 'bellman-ford',
        idea: 'Calcula caminhos mínimos por programação dinâmica. Em vez de "fechar" um vértice por iteração, como Dijkstra, examina todas as arestas a cada iteração. Como qualquer caminho em um grafo com n vértices possui no máximo n − 1 arestas, n − 1 iterações bastam.',
        pseudocode: [
            'Operação de relaxação',
            '  se dist[v] + d    < dist[w] então   // aresta (v, w) está tensa?',
            '                vw',
            '    dist[w] ← dist[v] + d',
            '                          vw',
            '    pred[w] ← v',
            '',
            'Método de Bellman-Ford',
            '  1. para todo vértice v ∈ V(G) faça',
            '       dist[v] ← ∞; pred[v] ← nulo',
            '  2. dist[s] ← 0',
            '  3. para i = 1, . . ., | V(G) | − 1 faça',
            '       para cada (v, w) ∈ E(G) faça',
            '         se dist[w] > dist[v] + d    então   // aresta tensa?',
            '                                  vw',
            '           dist[w] ← dist[v] + d',
            '                                vw',
            '           pred[w] ← v',
            '',
            '  Se ainda houver aresta tensa após a última iteração,',
            '  então existe um ciclo de custo negativo no grafo.',
        ],
        invariant:
            'Após a i-ésima iteração, dist[w] é no máximo o custo do menor caminho de s a w que usa até i arestas.',
        pitfalls: [
            'Se, em alguma iteração, nenhuma aresta estiver tensa, o algoritmo pode terminar: as iterações seguintes não trariam atualizações.',
            'Havendo ciclo de custo negativo entre s e t, não existe caminho mínimo entre eles; sem esse ciclo, o caminho mínimo é simples (não repete vértices).',
            'Aresta não direcionada com custo negativo já é, por si só, um ciclo de custo negativo.',
        ],
    },
    {
        id: 'floyd-warshall',
        idea: 'Programação dinâmica sobre o conjunto de vértices intermediários permitidos. Numerados os vértices de 1 a n, distᵏ[i, j] é a distância entre i e j usando como intermediários apenas os vértices de { 1, 2, . . ., k }.',
        pseudocode: [
            'Relaxação do comprimento dos caminhos',
            '  distᵏ[i, j] = min( distᵏ⁻¹[i, j],',
            '                     distᵏ⁻¹[i, k] + distᵏ⁻¹[k, j] )',
            '  com dist⁰[i, j] = d   se (i, j) ∈ E(G); ∞ caso contrário;',
            '                     ij',
            '  e dist⁰[i, i] = 0',
            '',
            'Método de Floyd-Warshall',
            '  1. para i = 1, . . ., n faça',
            '       para j = 1, . . ., n | j ≠ i faça',
            '         dist[i, j] ← ∞; pred[i, j] ← nulo',
            '       dist[i, i] ← 0;   pred[i, i] ← i',
            '  2. para toda aresta (i, j) ∈ E(G) faça',
            '       dist[i, j] ← d  ;  pred[i, j] ← i',
            '                     ij',
            '  3. para k = 1, . . ., n faça   // cada possível intermediário',
            '       para i = 1, . . ., n faça',
            '         para j = 1, . . ., n faça',
            '           se dist[i, j] > dist[i, k] + dist[k, j] então',
            '             dist[i, j] ← dist[i, k] + dist[k, j]',
            '             pred[i, j] ← pred[k, j]',
        ],
        invariant:
            'Ao final da rodada k, dist[i, j] é o custo do menor caminho de i a j que usa apenas { 1, . . ., k } como vértices intermediários; pred[i, j] guarda o penúltimo vértice desse caminho.',
        pitfalls: [
            'Trocar a ordem dos laços: k precisa ser o laço mais externo.',
            'Atualizar o predecessor com pred[i, k] em vez de pred[k, j] — pred[i, j] é o penúltimo vértice do caminho de i para j.',
            'Entrada negativa na diagonal, isto é, dist[i, i] < 0, indica ciclo de custo negativo.',
        ],
    },
    {
        id: 'ford-fulkerson',
        idea: 'Enquanto existir caminho aumentante da fonte s ao sumidouro t na rede residual G′(f), envia-se por ele o máximo possível — o gargalo δ — e a rede residual é atualizada. As arestas reversas permitem desfazer envios anteriores.',
        pseudocode: [
            'Rede residual G′(f) — V(G′) = V(G) e, para e = (v, w) ∈ E:',
            '  se f(e) < u(e): aresta direta (v, w) com u (e) = u(e) − f(e)',
            '                                            r',
            '  se f(e) > 0:    aresta reversa (w, v) com capacidade f(e)',
            '',
            'Método de Ford-Fulkerson',
            '  1. para toda aresta e ∈ E(G) faça  f(e) ← 0',
            '  2. Construir a rede residual G′(f)',
            '  3. enquanto existir caminho aumentante P em G′(f) efetuar',
            '     a. δ ← min { u (e) | e ∈ P }        // "gargalo" de P',
            '                    r',
            '     b. para cada aresta (v, w) ∈ P faça',
            '        i.  se (v, w) for aresta direta então',
            '              f(v, w) ← f(v, w) + δ      // aumentar fluxo',
            '        ii. senão',
            '              f(w, v) ← f(w, v) − δ      // reduzir fluxo',
            '     c. Atualizar a rede residual G′(f)',
        ],
        invariant:
            'O fluxo f respeita sempre a condição de capacidade, 0 ≤ f(e) ≤ u(e), e a condição de conservação em todo nó interno. Pelo teorema do fluxo máximo e corte mínimo, ao final o valor do fluxo iguala a capacidade do corte s-t mínimo.',
        pitfalls: [
            'Esquecer de criar a aresta reversa na rede residual, o que impede desfazer envios feitos em iterações anteriores.',
            'Escolher caminhos aumentantes arbitrários: com capacidades irracionais o método pode não terminar. Escolher sempre o caminho aumentante com menos arestas (busca em largura) é o método de Edmonds-Karp.',
            'Assumir que o corte mínimo é qualquer corte: na solução ótima, S é o conjunto dos vértices alcançáveis a partir da fonte s na rede residual final.',
        ],
    },
];

export const documentationById = new Map(documentation.map((entry) => [entry.id, entry]));
